### PR TITLE
Loosen up Jedi version requirement

### PR DESCRIPTION
**Pull request by alanhdu**
See: https://github.com/conda-forge/xeus-python-feedstock/issues/77

### CODE REVIEW

**Comment by alanhdu** [comment]
@conda-forge-admin, please rerender

**Comment by alanhdu** [comment]
Hm... I'm not sure why the Travis build failed. The error message is pretty cryptic.

**Comment by alanhdu** [comment]
@SylvainCorlay -- sorry to bother you, but would you mind taking a look at this PR to see if this correctly loosens the version requirement?

**Comment by martinRenou** [comment]
Is is really safe ton unpin?

**Comment by martinRenou** [comment]
Any jedi API change would break xeus-python

**Comment by alanhdu** [comment]
Quoting from #77:

> From browsing the original repo (https://github.com/jupyter-xeus/xeus-python/blob/master/environment.yml), it looks like the upstream repo xeus-python doesn't pin a specific version of jedi, which indicates that it probably works fine against jedi 0.17 (and FWIW, I have noticed no problems I forcibly pip install jedi=0.17.2 in my environment).

Given that the upstream repo is testing against the latest version of jedi, I think this should be ok.

**Comment by JohanMabille** [comment]
The `environment.yml` file is used for binder, not for testing. We pin `jedi 0.15.1` int the [tests](https://github.com/jupyter-xeus/xeus-python/blob/master/.travis.yml#L67).

I'm gonna remove that pin and see if it works.

**Pull request merged**
